* lots of tweaks, mostly on the train from Copenhagen

diff --git a/utils/Makefile.common b/utils/Makefile.common
--- a/utils/Makefile.common
+++ b/utils/Makefile.common
@@ -29,22 +29,26 @@ netbsd:
 # Requires: sshfs mount at ~/sshfs/msigner1
 # TDNS_SRC ?= ~/src/git/tdns
 # TDNS_AWS_DIR ?= ~/sshfs/msigner1/src/tdns
+# TDNS_NBSD_DIR=root@godev101.axfr.net:/usr/store/axfr.net/go/tdns.rsync
 
 # mount:
 # sshfs ubuntu@msigner1.ddns.axfr.net:/home/ubuntu ~/sshfs/msigner1 
 # umount:
 # umount ~/sshfs/msigner1
 
-TDNS_SRC ?= /Users/johani/src/git/tdns
-TDNS_AWS_DIR ?= /Users/johani/sshfs/msigner1/src/tdns
+# TDNS_SRC ?= /Users/johani/src/git/tdns
+# TDNS_AWS_DIR ?= /Users/johani/sshfs/msigner1/src/tdns
 
 johaniaws:
 	rsync --delete --exclude=.git --exclude-from=${TDNS_SRC}/.gitignore --exclude-from=${TDNS_SRC}/.rsyncignore -avx ${TDNS_SRC}/ ${TDNS_AWS_DIR}/
 
 johaninbsd:
-	echo foo
+	@if [ -z "$$TDNS_SRC" ]; then \
+	   echo "Error: TDNS_SRC is not set (required for johaninbsd)"; \
+	   exit 1; \
+	fi
 	@if [ -n "$$TDNS_NBSD_DIR" ]; then \
-	   echo rsyncing to ${TDNS_NBSD_DIR} ; \
+	   echo rsyncing from ${TDNS_SRC} to ${TDNS_NBSD_DIR} ; \
 	   (cd ${TDNS_SRC} ; rsync --delete --exclude=.git \
 		--exclude-from=${TDNS_SRC}/.gitignore --exclude-from=${TDNS_SRC}/.rsyncignore \
 		-avx ${TDNS_SRC}/ ${TDNS_NBSD_DIR}/ );\
